version: "3.7"
services:
  db:
    platform: linux/x86_64
    image: mysql:5.7.35
    restart: "no"
    environment:
      MYSQL_DATABASE: 'neighbor' # So you don't have to use root, but you can if you like
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      MYSQL_USER: 'neighbor_dev'
      MYSQL_PASSWORD: 'abcd1234'
    ports: # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
