spring:
datasource:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/neighbor
  username: neighbor_dev
  password: abcd1234
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
#spring.datasource.url=jdbc:mysql://localhost:52000/neighbor
#spring.datasource.username= neighbor_user
#spring.datasource.password=
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#spring.jpa.database-platform = org.hibernate.dialect.MySQL5Dialect
#spring.jpa.generate-ddl=true
#spring.jpa.hibernate.ddl-auto = update